#!/bin/bash
# Installiert AIOS als OpenCode Custom Tool im aktuellen Projekt.
# Usage: bash /path/to/AIOS/scripts/install-opencode-tool.sh [--global]

set -euo pipefail

AIOS_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ "${1:-}" == "--global" ]]; then
  TOOL_DIR="${HOME}/.config/opencode/tools"
  echo "Installiere AIOS-Tool global in ${TOOL_DIR}..."
else
  TOOL_DIR=".opencode/tools"
  echo "Installiere AIOS-Tool projekt-lokal in ${TOOL_DIR}..."
fi

mkdir -p "$TOOL_DIR"

# Generate tool file with resolved AIOS path
cat > "$TOOL_DIR/aios.ts" << ENDOFFILE
/**
 * AIOS Custom Tool für OpenCode
 * Auto-generated by install-opencode-tool.sh
 * AIOS-Pfad: ${AIOS_DIR}
 */
import { tool } from "@opencode-ai/plugin";
import { execSync } from "child_process";

const AIOS_BIN = "${AIOS_DIR}/node_modules/.bin/tsx ${AIOS_DIR}/src/cli.ts";

export default tool({
  description:
    "AIOS AI-Orchestrierung: Code Review, Security Review, Zusammenfassungen, Requirements-Extraktion, Compliance-Reports und mehr. Nutze command='patterns' um verfügbare Patterns zu sehen.",
  args: {
    command: tool.schema
      .enum(["run", "plan", "orchestrate", "patterns"])
      .describe("'run' = Pattern, 'plan' = planen, 'orchestrate' = dynamisch, 'patterns' = Liste"),
    pattern: tool.schema.string().optional().describe("Pattern-Name für 'run'"),
    input: tool.schema.string().optional().describe("Input-Text oder Aufgabe"),
  },
  async execute(args) {
    let cmd = "";
    switch (args.command) {
      case "run":
        if (!args.pattern || !args.input) return "Fehler: 'run' braucht pattern und input";
        cmd = \`echo \${JSON.stringify(args.input || "")} | \${AIOS_BIN} run \${args.pattern}\`;
        break;
      case "plan":
        cmd = \`\${AIOS_BIN} plan \${JSON.stringify(args.input || "")}\`;
        break;
      case "orchestrate":
        cmd = \`\${AIOS_BIN} \${JSON.stringify(args.input || "")}\`;
        break;
      case "patterns":
        cmd = \`\${AIOS_BIN} patterns list\`;
        break;
    }
    try {
      return execSync(cmd, { encoding: "utf-8", timeout: 120000, env: process.env });
    } catch (e: any) {
      return "AIOS Fehler: " + (e.stderr || e.message);
    }
  },
});
ENDOFFILE

echo "✅ AIOS Custom Tool installiert in ${TOOL_DIR}/aios.ts"
echo "   OpenCode kann jetzt AIOS-Patterns als Tool nutzen."
echo ""
echo "   Tipp: In OpenCode, frage den Agent:"
echo "   \"Nutze aios mit command=patterns um verfügbare Patterns zu sehen\""
