import {
  existsSync, mkdirSync, writeFileSync, readFileSync, renameSync,
} from "fs";
import { join, dirname } from "path";
import { tmpdir } from "os";
import { randomUUID } from "crypto";
import chalk from "chalk";
import type { ContextConfig } from "../types.js";
import { serializeContext, parseContextYaml } from "./schema.js";

// ─── Types ───────────────────────────────────────────────

export interface GenerateResult {
  created: string[];
  modified: string[];
  skipped: string[];
}

export interface GenerateOptions {
  refresh?: boolean;
  cwd?: string;
  skipClaudeMdPrompt?: boolean;
  patchClaudeMd?: boolean;
}

// ─── Generator ───────────────────────────────────────────

/**
 * Generate the .aios/ directory tree from a validated ContextConfig.
 * Returns a summary of what was created/modified/skipped.
 */
export function generate(
  context: ContextConfig,
  options: GenerateOptions = {},
): GenerateResult {
  const cwd = options.cwd ?? process.cwd();
  const aiosDir = join(cwd, ".aios");
  const result: GenerateResult = { created: [], modified: [], skipped: [] };

  if (options.refresh) {
    return refreshFromExisting(cwd, result);
  }

  // ─── Create directory structure ─────────────────────
  const dirs = [
    aiosDir,
    join(aiosDir, "patterns"),
    join(aiosDir, "knowledge"),
    join(aiosDir, "knowledge", "decisions"),
    join(aiosDir, "knowledge", "requirements"),
    join(aiosDir, "knowledge", "facts"),
  ];

  for (const dir of dirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
  }

  // ─── Write .gitkeep files ───────────────────────────
  const gitkeeps = [
    join(aiosDir, "patterns", ".gitkeep"),
    join(aiosDir, "knowledge", "decisions", ".gitkeep"),
    join(aiosDir, "knowledge", "requirements", ".gitkeep"),
    join(aiosDir, "knowledge", "facts", ".gitkeep"),
  ];

  for (const gk of gitkeeps) {
    if (!existsSync(gk)) {
      writeFileAtomic(gk, "");
      result.created.push(gk);
    }
  }

  // ─── Write .gitignore ──────────────────────────────
  const gitignorePath = join(aiosDir, ".gitignore");
  if (!existsSync(gitignorePath)) {
    writeFileAtomic(gitignorePath, [
      "# AIOS generated .gitignore",
      "# Knowledge data (project-specific, not committed)",
      "knowledge/",
      "",
      "# Keep context.yaml and agent-instructions.md tracked",
      "!context.yaml",
      "!agent-instructions.md",
      "!.gitignore",
      "",
    ].join("\n"));
    result.created.push(gitignorePath);
  }

  // ─── Write context.yaml ────────────────────────────
  const contextPath = join(aiosDir, "context.yaml");
  const contextContent = "# AIOS Project Context\n# Regenerate with: aios init --refresh\n\n" + serializeContext(context);
  writeFileAtomic(contextPath, contextContent);
  result.created.push(contextPath);

  // ─── Write agent-instructions.md ───────────────────
  const instructionsPath = join(aiosDir, "agent-instructions.md");
  const instructions = renderAgentInstructions(context);
  writeFileAtomic(instructionsPath, instructions);
  result.created.push(instructionsPath);

  // ─── Patch CLAUDE.md ───────────────────────────────
  if (options.patchClaudeMd !== false) {
    const claudeMdResult = handleClaudeMd(cwd, context, options);
    if (claudeMdResult === "created") {
      result.created.push(join(cwd, "CLAUDE.md"));
    } else if (claudeMdResult === "modified") {
      result.modified.push(join(cwd, "CLAUDE.md"));
    } else if (claudeMdResult === "skipped") {
      result.skipped.push(join(cwd, "CLAUDE.md"));
    }
  }

  return result;
}

// ─── Refresh Mode ────────────────────────────────────────

function refreshFromExisting(cwd: string, result: GenerateResult): GenerateResult {
  const contextPath = join(cwd, ".aios", "context.yaml");
  if (!existsSync(contextPath)) {
    throw new Error("No .aios/context.yaml found. Run aios init first.");
  }

  const raw = readFileSync(contextPath, "utf-8");
  const context = parseContextYaml(raw);

  const instructionsPath = join(cwd, ".aios", "agent-instructions.md");
  const instructions = renderAgentInstructions(context);
  writeFileAtomic(instructionsPath, instructions);
  result.modified.push(instructionsPath);

  return result;
}

// ─── Template Rendering ──────────────────────────────────

function renderAgentInstructions(ctx: ContextConfig): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();

  lines.push("# AIOS Agent Instructions");
  lines.push(`# Generated by: aios init (${timestamp})`);
  lines.push("# Regenerate with: aios init --refresh");
  lines.push("# DO NOT HAND-EDIT — modify .aios/context.yaml and re-run aios init --refresh");
  lines.push("");

  if (ctx.aios?.path) {
    lines.push("## AIOS Location");
    lines.push(`Path: ${ctx.aios.path}`);
    lines.push("");

    if (ctx.aios.readOnly) {
      lines.push("## ⛔ READ-ONLY CONSTRAINT");
      lines.push(`The AIOS directory (${ctx.aios.path}) is READ-ONLY infrastructure.`);
      lines.push("");
      lines.push("NEVER modify, create, or delete files inside AIOS. This includes:");
      lines.push("- patterns/ — use .aios/patterns/ for project-local overrides instead");
      lines.push("- personas/ — use .aios/context.yaml to configure active personas");
      lines.push("- src/ — never touch AIOS source code from a project context");
      lines.push("- docs/ — reference only");
      lines.push("");
      lines.push("If a pattern doesn't fit this project → override it in .aios/patterns/");
      lines.push("If AIOS has a bug → inform the user, do not attempt to fix it");
      lines.push("");
    }
  }

  lines.push("## Project Context");
  lines.push(`Name: ${ctx.name}`);
  if (ctx.project?.domain) lines.push(`Domain: ${ctx.project.domain}`);
  if (ctx.project?.language) lines.push(`Language: ${ctx.project.language}`);
  if (ctx.project?.repo) lines.push(`Repository: ${ctx.project.repo}`);
  lines.push(`Type: ${ctx.type}`);
  lines.push("");

  lines.push("## Compliance");
  if (ctx.compliance?.standards && ctx.compliance.standards.length > 0) {
    for (const std of ctx.compliance.standards) {
      lines.push(`- ${std.id}${std.level ? ` (${std.level})` : ""}`);
    }
  } else {
    lines.push("No compliance standards configured.");
  }
  if (ctx.compliance?.requireTraceability) {
    lines.push(`Traceability required: ${ctx.compliance.requireTraceability}`);
  }
  lines.push("");

  lines.push("## Available Personas");
  lines.push("Team wird dynamisch pro Task zusammengestellt.");
  if (ctx.personas?.active) {
    for (const persona of ctx.personas.active) {
      lines.push(`- ${persona}`);
    }
  }
  lines.push("");

  lines.push("## Provider Routing");
  const routingEntries = Object.entries(ctx.providers?.routing ?? {});
  if (routingEntries.length > 0) {
    for (const [key, value] of routingEntries) {
      lines.push(`- ${key}: ${value}`);
    }
  } else {
    lines.push("Default provider routing (no overrides).");
  }
  lines.push("");

  lines.push("## Pattern Resolution Order");
  if (ctx.aios?.path) {
    lines.push("1. .aios/patterns/<name>/system.md  (project override, wins)");
    lines.push(`2. ${ctx.aios.path}/patterns/<name>/system.md  (default, fallback)`);
    lines.push("");
    lines.push("To override a pattern:");
    lines.push("  mkdir -p .aios/patterns/<pattern-name>");
    lines.push(`  cp ${ctx.aios.path}/patterns/<pattern-name>/system.md .aios/patterns/<pattern-name>/`);
    lines.push("  # Edit the local copy — AIOS will use it instead of the default");
  } else {
    lines.push("1. .aios/patterns/<name>/system.md  (project override, wins)");
    lines.push("2. patterns/<name>/system.md  (default, fallback)");
  }
  lines.push("");

  if (ctx.capabilities && ctx.capabilities.length > 0) {
    lines.push("## Capabilities");
    for (const cap of ctx.capabilities) {
      lines.push(`- ${cap.id}: ${cap.description}`);
    }
    lines.push("");
  }

  lines.push("## Commands");
  lines.push("  aios init                  # re-run wizard");
  lines.push("  aios init --refresh        # regenerate from context.yaml");
  lines.push('  aios "task description"    # dynamic routing');
  lines.push("  aios run <pattern>         # direct pattern execution");
  lines.push('  aios plan "task"           # show execution plan without running');
  lines.push("  aios patterns list         # list available patterns");
  lines.push("");

  return lines.join("\n");
}

// ─── CLAUDE.md Handling ──────────────────────────────────

const AIOS_POINTER = `## AIOS
This project uses AIOS for orchestrated development workflows.
Read .aios/agent-instructions.md for details.`;

function hasAiosPointer(content: string): boolean {
  return content.includes(".aios/agent-instructions.md") || content.includes("## AIOS");
}

function handleClaudeMd(
  cwd: string,
  _context: ContextConfig,
  options: GenerateOptions,
): "created" | "modified" | "skipped" | "exists" {
  const claudeMdPath = join(cwd, "CLAUDE.md");

  if (existsSync(claudeMdPath)) {
    const content = readFileSync(claudeMdPath, "utf-8");
    if (hasAiosPointer(content)) {
      return "exists"; // already has pointer, do nothing
    }
    // Exists but no pointer — append if allowed
    if (options.skipClaudeMdPrompt) {
      return "skipped";
    }
    // In non-interactive context (quick mode), append
    const newContent = content.trimEnd() + "\n\n" + AIOS_POINTER + "\n";
    writeFileAtomic(claudeMdPath, newContent);
    return "modified";
  }

  // Does not exist — create minimal one
  if (options.skipClaudeMdPrompt) {
    return "skipped";
  }

  const content = `# ${_context.name}\n\n${AIOS_POINTER}\n`;
  writeFileAtomic(claudeMdPath, content);
  return "created";
}

// ─── Atomic File Write ───────────────────────────────────

function writeFileAtomic(targetPath: string, content: string): void {
  const dir = dirname(targetPath);
  mkdirSync(dir, { recursive: true });
  const tmpPath = join(dir, `.tmp-${randomUUID()}`);
  writeFileSync(tmpPath, content, "utf-8");
  renameSync(tmpPath, targetPath);
}
